/**
 * Sample Recipes
 * 10+ German recipes for initial app data
 */

import { Recipe } from '../types';
import { generateId } from './utils';

export const sampleRecipes: Recipe[] = [
  {
    id: generateId(),
    name: 'Spaghetti Carbonara',
    description: 'Das klassische italienische Pasta-Gericht mit Ei, Speck und Parmesan. Cremig, einfach und unglaublich lecker!',
    image: 'https://images.unsplash.com/photo-1612874742237-6526221588e3?w=800',
    prepTime: 10,
    cookTime: 15,
    totalTime: 25,
    servings: 4,
    category: 'Hauptgericht',
    cuisine: 'Italienisch',
    tags: ['Pasta', 'Schnell', 'Klassiker', 'Einfach'],
    ingredients: [
      { id: generateId(), name: 'Spaghetti', amount: 400, unit: 'g', category: 'pantry', order: 0 },
      { id: generateId(), name: 'Speck oder Pancetta', amount: 150, unit: 'g', category: 'meat', order: 1 },
      { id: generateId(), name: 'Eier', amount: 4, unit: 'Stk', category: 'dairy', order: 2 },
      { id: generateId(), name: 'Parmesan', amount: 100, unit: 'g', category: 'dairy', order: 3 },
      { id: generateId(), name: 'Knoblauchzehen', amount: 2, unit: 'Stk', category: 'produce', order: 4 },
      { id: generateId(), name: 'schwarzer Pfeffer', amount: 1, unit: 'TL', category: 'pantry', order: 5 },
      { id: generateId(), name: 'Salz', amount: 1, unit: 'Prise', category: 'pantry', order: 6 },
    ],
    instructions: [
      { step: 1, text: 'Spaghetti in großem Salzwasser al dente kochen (ca. 8-10 Minuten).' },
      { step: 2, text: 'Währenddessen den Speck in kleine Würfel schneiden und in einer großen Pfanne knusprig anbraten.' },
      { step: 3, text: 'Knoblauch fein hacken und kurz mit dem Speck anschwitzen, dann entfernen.' },
      { step: 4, text: 'Eier mit geriebenem Parmesan und viel frisch gemahlenem Pfeffer verquirlen.' },
      { step: 5, text: 'Die heißen, abgetropften Spaghetti zur Pfanne geben und vom Herd nehmen.' },
      { step: 6, text: 'Die Ei-Käse-Mischung sofort unterheben, sodass eine cremige Sauce entsteht. Nicht mehr erhitzen!' },
      { step: 7, text: 'Sofort servieren und mit zusätzlichem Parmesan und Pfeffer garnieren.' },
    ],
    nutrition: {
      calories: '520 kcal',
      protein: '24g',
      carbs: '58g',
      fat: '22g',
    },
    isFavorite: true,
    createdAt: Date.now(),
    updatedAt: Date.now(),
  },
  {
    id: generateId(),
    name: 'Kartoffelgratin',
    description: 'Cremiges Kartoffelgratin mit Knoblauch und Käse - der perfekte Beilage oder Hauptgericht.',
    image: 'https://images.unsplash.com/photo-1626202269383-4f878545b2cc?w=800',
    prepTime: 20,
    cookTime: 60,
    totalTime: 80,
    servings: 6,
    category: 'Beilage',
    cuisine: 'Französisch',
    tags: ['Kartoffeln', 'Ofen', 'Käse', 'Vegetarisch'],
    ingredients: [
      { id: generateId(), name: 'Kartoffeln (festkochend)', amount: 1, unit: 'kg', category: 'produce', order: 0 },
      { id: generateId(), name: 'Sahne', amount: 400, unit: 'ml', category: 'dairy', order: 1 },
      { id: generateId(), name: 'Milch', amount: 200, unit: 'ml', category: 'dairy', order: 2 },
      { id: generateId(), name: 'Gouda (gerieben)', amount: 200, unit: 'g', category: 'dairy', order: 3 },
      { id: generateId(), name: 'Knoblauchzehen', amount: 3, unit: 'Stk', category: 'produce', order: 4 },
      { id: generateId(), name: 'Butter', amount: 30, unit: 'g', category: 'dairy', order: 5 },
      { id: generateId(), name: 'Muskat', amount: 0.5, unit: 'TL', category: 'pantry', order: 6 },
      { id: generateId(), name: 'Salz', amount: 1, unit: 'TL', category: 'pantry', order: 7 },
      { id: generateId(), name: 'Pfeffer', amount: 0.5, unit: 'TL', category: 'pantry', order: 8 },
    ],
    instructions: [
      { step: 1, text: 'Ofen auf 180°C (Ober-/Unterhitze) vorheizen.' },
      { step: 2, text: 'Kartoffeln schälen und in 3mm dicke Scheiben schneiden.' },
      { step: 3, text: 'Knoblauch fein hacken und mit Sahne, Milch, Salz, Pfeffer und Muskat verrühren.' },
      { step: 4, text: 'Eine Auflaufform mit Butter einfetten.' },
      { step: 5, text: 'Kartoffelscheiben lagenweise in die Form schichten, dazwischen etwas Käse streuen.' },
      { step: 6, text: 'Die Sahne-Mischung darübergießen und mit restlichem Käse bestreuen.' },
      { step: 7, text: 'Im Ofen ca. 60 Minuten backen, bis die Kartoffeln weich sind und die Oberfläche goldbraun ist.' },
    ],
    nutrition: {
      calories: '450 kcal',
      protein: '16g',
      carbs: '42g',
      fat: '26g',
    },
    isFavorite: false,
    createdAt: Date.now(),
    updatedAt: Date.now(),
  },
  {
    id: generateId(),
    name: 'Hähnchencurry mit Kokosmilch',
    description: 'Aromatisches Curry mit zartem Hähnchen, cremiger Kokosmilch und frischem Gemüse.',
    image: 'https://images.unsplash.com/photo-1565557623262-b51c2513a641?w=800',
    prepTime: 15,
    cookTime: 30,
    totalTime: 45,
    servings: 4,
    category: 'Hauptgericht',
    cuisine: 'Asiatisch',
    tags: ['Curry', 'Hähnchen', 'Kokos', 'Würzig'],
    ingredients: [
      { id: generateId(), name: 'Hähnchenbrustfilet', amount: 500, unit: 'g', category: 'meat', order: 0 },
      { id: generateId(), name: 'Kokosmilch', amount: 400, unit: 'ml', category: 'pantry', order: 1 },
      { id: generateId(), name: 'rote Currypaste', amount: 2, unit: 'EL', category: 'pantry', order: 2 },
      { id: generateId(), name: 'Zucchini', amount: 2, unit: 'Stk', category: 'produce', order: 3 },
      { id: generateId(), name: 'Paprika (rot)', amount: 2, unit: 'Stk', category: 'produce', order: 4 },
      { id: generateId(), name: 'Zwiebeln', amount: 2, unit: 'Stk', category: 'produce', order: 5 },
      { id: generateId(), name: 'Knoblauchzehen', amount: 3, unit: 'Stk', category: 'produce', order: 6 },
      { id: generateId(), name: 'Ingwer (frisch)', amount: 2, unit: 'cm', category: 'produce', order: 7 },
      { id: generateId(), name: 'Fischsauce', amount: 1, unit: 'EL', category: 'pantry', order: 8 },
      { id: generateId(), name: 'Limette', amount: 1, unit: 'Stk', category: 'produce', order: 9 },
      { id: generateId(), name: 'Basilikum (frisch)', amount: 1, unit: 'Bund', category: 'produce', order: 10 },
      { id: generateId(), name: 'Jasminreis', amount: 300, unit: 'g', category: 'pantry', order: 11 },
    ],
    instructions: [
      { step: 1, text: 'Reis nach Packungsanweisung kochen.' },
      { step: 2, text: 'Hähnchen in mundgerechte Stücke schneiden. Gemüse in Streifen schneiden.' },
      { step: 3, text: 'Zwiebeln, Knoblauch und Ingwer fein hacken.' },
      { step: 4, text: 'Öl in einem Wok oder großen Topf erhitzen. Hähnchen scharf anbraten und herausnehmen.' },
      { step: 5, text: 'Zwiebeln, Knoblauch und Ingwer anschwitzen. Currypaste zugeben und kurz mitrösten.' },
      { step: 6, text: 'Kokosmilch und Fischsauce zugeben, aufkochen lassen.' },
      { step: 7, text: 'Gemüse zugeben und 10-12 Minuten köcheln lassen.' },
      { step: 8, text: 'Hähnchen zurück in den Topf geben und weitere 5 Minuten köcheln.' },
      { step: 9, text: 'Mit Limettensaft abschmecken und mit frischem Basilikum garnieren.' },
    ],
    nutrition: {
      calories: '480 kcal',
      protein: '35g',
      carbs: '48g',
      fat: '18g',
    },
    isFavorite: true,
    createdAt: Date.now(),
    updatedAt: Date.now(),
  },
  {
    id: generateId(),
    name: 'Griechischer Salat',
    description: 'Erfrischender Salat mit Tomaten, Gurken, Oliven und Feta - ein mediterraner Klassiker.',
    image: 'https://images.unsplash.com/photo-1540189549336-e6e99c3679fe?w=800',
    prepTime: 15,
    cookTime: 0,
    totalTime: 15,
    servings: 4,
    category: 'Salat',
    cuisine: 'Griechisch',
    tags: ['Salat', 'Vegetarisch', 'Gesund', 'Schnell'],
    ingredients: [
      { id: generateId(), name: 'Tomaten', amount: 4, unit: 'Stk', category: 'produce', order: 0 },
      { id: generateId(), name: 'Gurke', amount: 2, unit: 'Stk', category: 'produce', order: 1 },
      { id: generateId(), name: 'rote Zwiebel', amount: 1, unit: 'Stk', category: 'produce', order: 2 },
      { id: generateId(), name: 'grüne Paprika', amount: 1, unit: 'Stk', category: 'produce', order: 3 },
      { id: generateId(), name: 'Feta', amount: 200, unit: 'g', category: 'dairy', order: 4 },
      { id: generateId(), name: 'Kalamata-Oliven', amount: 100, unit: 'g', category: 'pantry', order: 5 },
      { id: generateId(), name: 'Olivenöl', amount: 4, unit: 'EL', category: 'pantry', order: 6 },
      { id: generateId(), name: 'Oregano (getrocknet)', amount: 1, unit: 'TL', category: 'pantry', order: 7 },
      { id: generateId(), name: 'Zitrone', amount: 1, unit: 'Stk', category: 'produce', order: 8 },
      { id: generateId(), name: 'Salz', amount: 1, unit: 'Prise', category: 'pantry', order: 9 },
      { id: generateId(), name: 'Pfeffer', amount: 1, unit: 'Prise', category: 'pantry', order: 10 },
    ],
    instructions: [
      { step: 1, text: 'Tomaten in Spalten, Gurke in Scheiben schneiden.' },
      { step: 2, text: 'Zwiebel in feine Ringe, Paprika in Streifen schneiden.' },
      { step: 3, text: 'Alle Gemüse in einer großen Schüssel vermischen.' },
      { step: 4, text: 'Feta in Würfel schneiden und über den Salat geben.' },
      { step: 5, text: 'Oliven zugeben.' },
      { step: 6, text: 'Olivenöl, Zitronensaft, Oregano, Salz und Pfeffer zu einem Dressing verrühren.' },
      { step: 7, text: 'Dressing über den Salat träufeln und vorsichtig unterheben.' },
      { step: 8, text: 'Sofort servieren oder 10 Minuten ziehen lassen.' },
    ],
    nutrition: {
      calories: '280 kcal',
      protein: '10g',
      carbs: '12g',
      fat: '22g',
    },
    isFavorite: false,
    createdAt: Date.now(),
    updatedAt: Date.now(),
  },
  {
    id: generateId(),
    name: 'Rinder-Gulasch',
    description: 'Deftiges Gulasch mit zartem Rindfleisch in einer reichhaltigen Paprikasauce.',
    image: 'https://images.unsplash.com/photo-1534939561126-855b8675edd7?w=800',
    prepTime: 30,
    cookTime: 120,
    totalTime: 150,
    servings: 6,
    category: 'Hauptgericht',
    cuisine: 'Ungarisch',
    tags: ['Fleisch', 'Eintopf', 'Herzhaft', 'Klassiker'],
    ingredients: [
      { id: generateId(), name: 'Rindergulasch', amount: 1, unit: 'kg', category: 'meat', order: 0 },
      { id: generateId(), name: 'Zwiebeln', amount: 3, unit: 'Stk', category: 'produce', order: 1 },
      { id: generateId(), name: 'Paprika (rot)', amount: 2, unit: 'Stk', category: 'produce', order: 2 },
      { id: generateId(), name: 'Tomatenmark', amount: 3, unit: 'EL', category: 'pantry', order: 3 },
      { id: generateId(), name: 'Rinderbrühe', amount: 500, unit: 'ml', category: 'pantry', order: 4 },
      { id: generateId(), name: 'Rotwein', amount: 200, unit: 'ml', category: 'beverages', order: 5 },
      { id: generateId(), name: 'Knoblauchzehen', amount: 3, unit: 'Stk', category: 'produce', order: 6 },
      { id: generateId(), name: 'Paprikapulver (edelsüß)', amount: 2, unit: 'EL', category: 'pantry', order: 7 },
      { id: generateId(), name: 'Paprikapulver (rosenscharf)', amount: 1, unit: 'TL', category: 'pantry', order: 8 },
      { id: generateId(), name: 'Kümmel', amount: 1, unit: 'TL', category: 'pantry', order: 9 },
      { id: generateId(), name: 'Lorbeerblätter', amount: 2, unit: 'Stk', category: 'pantry', order: 10 },
      { id: generateId(), name: 'Tomaten (Dosentomaten)', amount: 400, unit: 'g', category: 'pantry', order: 11 },
      { id: generateId(), name: 'Öl', amount: 3, unit: 'EL', category: 'pantry', order: 12 },
      { id: generateId(), name: 'Salz', amount: 1, unit: 'TL', category: 'pantry', order: 13 },
      { id: generateId(), name: 'Pfeffer', amount: 0.5, unit: 'TL', category: 'pantry', order: 14 },
    ],
    instructions: [
      { step: 1, text: 'Fleisch in Würfel schneiden, salzen und pfeffern.' },
      { step: 2, text: 'Zwiebeln in feine Würfel, Paprika in Streifen schneiden.' },
      { step: 3, text: 'Öl in einem großen Topf erhitzen und Fleisch portionsweise scharf anbraten. Herausnehmen.' },
      { step: 4, text: 'Zwiebeln im selben Topf glasig dünsten, Knoblauch zugeben.' },
      { step: 5, text: 'Tomatenmark zugeben und kurz anschwitzen.' },
      { step: 6, text: 'Paprikapulver und Kümmel zugeben, kurz mitrösten.' },
      { step: 7, text: 'Mit Rotwein ablöschen und einkochen lassen.' },
      { step: 8, text: 'Fleisch zurück in den Topf geben, Brühe und Dosentomaten zugeben.' },
      { step: 9, text: 'Lorbeerblätter zugeben, aufkochen und bei kleiner Hitze 1,5-2 Stunden schmoren lassen.' },
      { step: 10, text: 'Paprikastreifen zugeben und weitere 20 Minuten köcheln lassen.' },
      { step: 11, text: 'Mit Salz und Pfeffer abschmecken, Lorbeerblätter entfernen.' },
    ],
    nutrition: {
      calories: '420 kcal',
      protein: '38g',
      carbs: '14g',
      fat: '24g',
    },
    isFavorite: true,
    createdAt: Date.now(),
    updatedAt: Date.now(),
  },
  {
    id: generateId(),
    name: 'Pfannkuchen (Crêpes)',
    description: 'Dünne, zarte Pfannkuchen - perfekt für süße oder herzhafte Füllungen.',
    image: 'https://images.unsplash.com/photo-1506084868230-bb9d95c24759?w=800',
    prepTime: 10,
    cookTime: 20,
    totalTime: 30,
    servings: 4,
    category: 'Dessert',
    cuisine: 'Französisch',
    tags: ['Süß', 'Frühstück', 'Einfach', 'Kinder'],
    ingredients: [
      { id: generateId(), name: 'Mehl', amount: 200, unit: 'g', category: 'pantry', order: 0 },
      { id: generateId(), name: 'Milch', amount: 400, unit: 'ml', category: 'dairy', order: 1 },
      { id: generateId(), name: 'Eier', amount: 3, unit: 'Stk', category: 'dairy', order: 2 },
      { id: generateId(), name: 'Zucker', amount: 1, unit: 'EL', category: 'pantry', order: 3 },
      { id: generateId(), name: 'Butter (geschmolzen)', amount: 30, unit: 'g', category: 'dairy', order: 4 },
      { id: generateId(), name: 'Salz', amount: 0.5, unit: 'TL', category: 'pantry', order: 5 },
      { id: generateId(), name: 'Butter (zum Braten)', amount: 20, unit: 'g', category: 'dairy', order: 6 },
    ],
    instructions: [
      { step: 1, text: 'Mehl, Zucker und Salz in einer Schüssel vermischen.' },
      { step: 2, text: 'Eier und die Hälfte der Milch zugeben und zu einem glatten Teig verrühren.' },
      { step: 3, text: 'Restliche Milch und geschmolzene Butter unterrühren.' },
      { step: 4, text: 'Teig 15 Minuten quellen lassen.' },
      { step: 5, text: 'Eine Pfanne bei mittlerer Hitze erhitzen und mit etwas Butter einfetten.' },
      { step: 6, text: 'Eine Kelle Teig in die Pfanne geben und schwenken, um den Boden zu bedecken.' },
      { step: 7, text: 'Ca. 1-2 Minuten backen, bis der Rand goldbraun wird.' },
      { step: 8, text: 'Wenden und weitere 30 Sekunden backen.' },
      { step: 9, text: 'Warm halten und restlichen Teig ebenso verarbeiten.' },
    ],
    nutrition: {
      calories: '320 kcal',
      protein: '12g',
      carbs: '42g',
      fat: '14g',
    },
    isFavorite: false,
    createdAt: Date.now(),
    updatedAt: Date.now(),
  },
  {
    id: generateId(),
    name: 'Gemüse-Lasagne',
    description: 'Vegetarische Lasagne mit buntem Gemüse und cremiger Béchamelsauce.',
    image: 'https://images.unsplash.com/photo-1574868235872-1663edcb4569?w=800',
    prepTime: 30,
    cookTime: 45,
    totalTime: 75,
    servings: 6,
    category: 'Hauptgericht',
    cuisine: 'Italienisch',
    tags: ['Vegetarisch', 'Ofen', 'Gemüse', 'Familie'],
    ingredients: [
      { id: generateId(), name: 'Lasagneblätter', amount: 12, unit: 'Stk', category: 'pantry', order: 0 },
      { id: generateId(), name: 'Zucchini', amount: 2, unit: 'Stk', category: 'produce', order: 1 },
      { id: generateId(), name: 'Aubergine', amount: 1, unit: 'Stk', category: 'produce', order: 2 },
      { id: generateId(), name: 'Paprika (gelb)', amount: 2, unit: 'Stk', category: 'produce', order: 3 },
      { id: generateId(), name: 'Champignons', amount: 250, unit: 'g', category: 'produce', order: 4 },
      { id: generateId(), name: 'Zwiebeln', amount: 2, unit: 'Stk', category: 'produce', order: 5 },
      { id: generateId(), name: 'Knoblauchzehen', amount: 2, unit: 'Stk', category: 'produce', order: 6 },
      { id: generateId(), name: 'passierte Tomaten', amount: 500, unit: 'ml', category: 'pantry', order: 7 },
      { id: generateId(), name: 'Mozzarella', amount: 250, unit: 'g', category: 'dairy', order: 8 },
      { id: generateId(), name: 'Parmesan (gerieben)', amount: 100, unit: 'g', category: 'dairy', order: 9 },
      { id: generateId(), name: 'Butter', amount: 50, unit: 'g', category: 'dairy', order: 10 },
      { id: generateId(), name: 'Mehl', amount: 50, unit: 'g', category: 'pantry', order: 11 },
      { id: generateId(), name: 'Milch', amount: 500, unit: 'ml', category: 'dairy', order: 12 },
      { id: generateId(), name: 'Olivenöl', amount: 3, unit: 'EL', category: 'pantry', order: 13 },
      { id: generateId(), name: 'Oregano', amount: 1, unit: 'TL', category: 'pantry', order: 14 },
      { id: generateId(), name: 'Basilikum (frisch)', amount: 1, unit: 'Bund', category: 'produce', order: 15 },
      { id: generateId(), name: 'Salz', amount: 1, unit: 'TL', category: 'pantry', order: 16 },
      { id: generateId(), name: 'Pfeffer', amount: 0.5, unit: 'TL', category: 'pantry', order: 17 },
    ],
    instructions: [
      { step: 1, text: 'Ofen auf 180°C vorheizen.' },
      { step: 2, text: 'Gemüse in kleine Würfel schneiden. Zwiebeln und Knoblauch fein hacken.' },
      { step: 3, text: 'Öl in einer großen Pfanne erhitzen. Zwiebeln und Knoblauch anschwitzen.' },
      { step: 4, text: 'Gemüse zugeben und 10 Minuten anbraten.' },
      { step: 5, text: 'Passierte Tomaten und Oregano zugeben, 10 Minuten köcheln lassen.' },
      { step: 6, text: 'Für die Béchamel: Butter schmelzen, Mehl zugeben und anschwitzen.' },
      { step: 7, text: 'Milch nach und nach unter ständigem Rühren zugeben, aufkochen lassen.' },
      { step: 8, text: 'Mit Salz, Pfeffer und Muskat abschmecken.' },
      { step: 9, text: 'Eine Auflaufform einfetten. Abwechselnd Gemüsesauce, Lasagneblätter und Béchamel schichten.' },
      { step: 10, text: 'Mit Béchamel abschließen, Mozzarella und Parmesan darüberstreuen.' },
      { step: 11, text: 'Ca. 40-45 Minuten backen, bis die Oberfläche goldbraun ist.' },
      { step: 12, text: 'Vor dem Servieren 10 Minuten ruhen lassen.' },
    ],
    nutrition: {
      calories: '380 kcal',
      protein: '18g',
      carbs: '42g',
      fat: '16g',
    },
    isFavorite: false,
    createdAt: Date.now(),
    updatedAt: Date.now(),
  },
  {
    id: generateId(),
    name: 'Lachs mit Dill-Sauce',
    description: 'Zarter Lachs mit einer cremigen Dill-Sauce - ein elegantes Gericht für besondere Anlässe.',
    image: 'https://images.unsplash.com/photo-1467003909585-2f8a72700288?w=800',
    prepTime: 15,
    cookTime: 20,
    totalTime: 35,
    servings: 4,
    category: 'Hauptgericht',
    cuisine: 'Skandinavisch',
    tags: ['Fisch', 'Gesund', 'Elegant', 'Schnell'],
    ingredients: [
      { id: generateId(), name: 'Lachsfilet', amount: 600, unit: 'g', category: 'seafood', order: 0 },
      { id: generateId(), name: 'Sahne', amount: 200, unit: 'ml', category: 'dairy', order: 1 },
      { id: generateId(), name: 'Crème fraîche', amount: 100, unit: 'g', category: 'dairy', order: 2 },
      { id: generateId(), name: 'Zitrone', amount: 1, unit: 'Stk', category: 'produce', order: 3 },
      { id: generateId(), name: 'Dill (frisch)', amount: 1, unit: 'Bund', category: 'produce', order: 4 },
      { id: generateId(), name: 'Knoblauchzehe', amount: 1, unit: 'Stk', category: 'produce', order: 5 },
      { id: generateId(), name: 'Butter', amount: 30, unit: 'g', category: 'dairy', order: 6 },
      { id: generateId(), name: 'Salz', amount: 1, unit: 'TL', category: 'pantry', order: 7 },
      { id: generateId(), name: 'Pfeffer', amount: 0.5, unit: 'TL', category: 'pantry', order: 8 },
      { id: generateId(), name: 'Zucker', amount: 0.5, unit: 'TL', category: 'pantry', order: 9 },
      { id: generateId(), name: 'Basmatireis', amount: 300, unit: 'g', category: 'pantry', order: 10 },
    ],
    instructions: [
      { step: 1, text: 'Reis nach Packungsanweisung kochen.' },
      { step: 2, text: 'Lachsfilets waschen, trocken tupfen und mit Salz und Pfeffer würzen.' },
      { step: 3, text: 'Dill fein hacken, Zitrone auspressen.' },
      { step: 4, text: 'Für die Sauce: Sahne, Crème fraîche, Zitronensaft, Zucker und gehackten Dill verrühren.' },
      { step: 5, text: 'Mit Salz und Pfeffer abschmecken.' },
      { step: 6, text: 'Butter in einer Pfanne erhitzen. Lachs mit der Hautseite nach unten hineinlegen.' },
      { step: 7, text: 'Ca. 4-5 Minuten braten, dann wenden und weitere 3-4 Minuten garen.' },
      { step: 8, text: 'Lachs herausnehmen und warm stellen.' },
      { step: 9, text: 'Sauce in die Pfanne geben und kurz aufwärmen.' },
      { step: 10, text: 'Lachs mit Reis und Sauce anrichten.' },
    ],
    nutrition: {
      calories: '450 kcal',
      protein: '32g',
      carbs: '38g',
      fat: '20g',
    },
    isFavorite: true,
    createdAt: Date.now(),
    updatedAt: Date.now(),
  },
  {
    id: generateId(),
    name: 'Apfelkuchen mit Streuseln',
    description: 'Saftiger Apfelkuchen mit knusprigen Streuseln - ein Klassiker für jede Jahreszeit.',
    image: 'https://images.unsplash.com/photo-1568571780765-9276ac8b75a2?w=800',
    prepTime: 30,
    cookTime: 50,
    totalTime: 80,
    servings: 12,
    category: 'Dessert',
    cuisine: 'Deutsch',
    tags: ['Kuchen', 'Süß', 'Backen', 'Apfel'],
    ingredients: [
      { id: generateId(), name: 'Äpfel (säuerlich)', amount: 1, unit: 'kg', category: 'produce', order: 0 },
      { id: generateId(), name: 'Mehl', amount: 400, unit: 'g', category: 'pantry', order: 1 },
      { id: generateId(), name: 'Butter (kalt)', amount: 250, unit: 'g', category: 'dairy', order: 2 },
      { id: generateId(), name: 'Zucker', amount: 200, unit: 'g', category: 'pantry', order: 3 },
      { id: generateId(), name: 'Eier', amount: 2, unit: 'Stk', category: 'dairy', order: 4 },
      { id: generateId(), name: 'Backpulver', amount: 2, unit: 'TL', category: 'pantry', order: 5 },
      { id: generateId(), name: 'Vanillezucker', amount: 1, unit: 'Pck', category: 'pantry', order: 6 },
      { id: generateId(), name: 'Zimt', amount: 1, unit: 'TL', category: 'pantry', order: 7 },
      { id: generateId(), name: 'Salz', amount: 0.5, unit: 'TL', category: 'pantry', order: 8 },
      { id: generateId(), name: 'Zitrone', amount: 1, unit: 'Stk', category: 'produce', order: 9 },
    ],
    instructions: [
      { step: 1, text: 'Ofen auf 180°C vorheizen. Springform (26cm) fetten und mit Mehl ausstäuben.' },
      { step: 2, text: 'Äpfel schälen, vierteln, entkernen und in Spalten schneiden. Mit Zitronensaft beträufeln.' },
      { step: 3, text: 'Für den Teig: 250g Mehl, Backpulver, 100g Zucker, Vanillezucker, Eier und 100g weiche Butter verkneten.' },
      { step: 4, text: 'Teig in die Form drücken und einen Rand hochziehen.' },
      { step: 5, text: 'Apfelspalten auf dem Teig verteilen und mit Zimt und 50g Zucker bestreuen.' },
      { step: 6, text: 'Für die Streusel: 150g Mehl, 150g Zucker und 150g kalte Butter zu Streuseln verkneten.' },
      { step: 7, text: 'Streusel über die Äpfel streuen.' },
      { step: 8, text: 'Im Ofen ca. 45-50 Minuten backen, bis die Streusel goldbraun sind.' },
      { step: 9, text: 'Auskühlen lassen und aus der Form lösen.' },
    ],
    nutrition: {
      calories: '320 kcal',
      protein: '4g',
      carbs: '48g',
      fat: '14g',
    },
    isFavorite: true,
    createdAt: Date.now(),
    updatedAt: Date.now(),
  },
  {
    id: generateId(),
    name: 'Bauerntopf mit Hackfleisch',
    description: 'Deftiger Eintopf mit Hackfleisch, Kartoffeln und Gemüse - schnell und sättigend.',
    image: 'https://images.unsplash.com/photo-1547592180-85f173990554?w=800',
    prepTime: 15,
    cookTime: 35,
    totalTime: 50,
    servings: 4,
    category: 'Hauptgericht',
    cuisine: 'Deutsch',
    tags: ['Eintopf', 'Hackfleisch', 'Einfach', 'Schnell'],
    ingredients: [
      { id: generateId(), name: 'Hackfleisch (gemischt)', amount: 400, unit: 'g', category: 'meat', order: 0 },
      { id: generateId(), name: 'Kartoffeln', amount: 500, unit: 'g', category: 'produce', order: 1 },
      { id: generateId(), name: 'Paprika (rot)', amount: 2, unit: 'Stk', category: 'produce', order: 2 },
      { id: generateId(), name: 'Zwiebeln', amount: 2, unit: 'Stk', category: 'produce', order: 3 },
      { id: generateId(), name: 'Knoblauchzehen', amount: 2, unit: 'Stk', category: 'produce', order: 4 },
      { id: generateId(), name: 'Tomaten (Dosentomaten)', amount: 400, unit: 'g', category: 'pantry', order: 5 },
      { id: generateId(), name: 'Tomatenmark', amount: 2, unit: 'EL', category: 'pantry', order: 6 },
      { id: generateId(), name: 'Paprikapulver', amount: 1, unit: 'EL', category: 'pantry', order: 7 },
      { id: generateId(), name: 'Thymian (getrocknet)', amount: 1, unit: 'TL', category: 'pantry', order: 8 },
      { id: generateId(), name: 'Öl', amount: 2, unit: 'EL', category: 'pantry', order: 9 },
      { id: generateId(), name: 'Salz', amount: 1, unit: 'TL', category: 'pantry', order: 10 },
      { id: generateId(), name: 'Pfeffer', amount: 0.5, unit: 'TL', category: 'pantry', order: 11 },
    ],
    instructions: [
      { step: 1, text: 'Kartoffeln schälen und in Würfel schneiden. Paprika in Streifen, Zwiebeln in Würfel schneiden.' },
      { step: 2, text: 'Knoblauch fein hacken.' },
      { step: 3, text: 'Öl in einem großen Topf erhitzen. Hackfleisch darin krümelig anbraten.' },
      { step: 4, text: 'Zwiebeln und Knoblauch zugeben und glasig dünsten.' },
      { step: 5, text: 'Paprikastreifen und Kartoffelwürfel zugeben.' },
      { step: 6, text: 'Tomatenmark und Paprikapulver zugeben, kurz anschwitzen.' },
      { step: 7, text: 'Dosentomaten und Thymian zugeben, aufkochen lassen.' },
      { step: 8, text: 'Bei mittlerer Hitze ca. 25-30 Minuten köcheln lassen, bis die Kartoffeln weich sind.' },
      { step: 9, text: 'Mit Salz und Pfeffer kräftig abschmecken.' },
    ],
    nutrition: {
      calories: '420 kcal',
      protein: '24g',
      carbs: '38g',
      fat: '20g',
    },
    isFavorite: false,
    createdAt: Date.now(),
    updatedAt: Date.now(),
  },
  {
    id: generateId(),
    name: 'Quiche Lorraine',
    description: 'Französische Speck-Zwiebel-Tarte mit cremiger Eier-Sahne-Füllung.',
    image: 'https://images.unsplash.com/photo-1608039829572-78524f79c4c7?w=800',
    prepTime: 25,
    cookTime: 40,
    totalTime: 65,
    servings: 6,
    category: 'Hauptgericht',
    cuisine: 'Französisch',
    tags: ['Tarte', 'Ofen', 'Französisch', 'Klassiker'],
    ingredients: [
      { id: generateId(), name: 'Mehl', amount: 250, unit: 'g', category: 'pantry', order: 0 },
      { id: generateId(), name: 'Butter (kalt)', amount: 125, unit: 'g', category: 'dairy', order: 1 },
      { id: generateId(), name: 'Ei', amount: 1, unit: 'Stk', category: 'dairy', order: 2 },
      { id: generateId(), name: 'Salz', amount: 0.5, unit: 'TL', category: 'pantry', order: 3 },
      { id: generateId(), name: 'Speck (gewürfelt)', amount: 200, unit: 'g', category: 'meat', order: 4 },
      { id: generateId(), name: 'Zwiebeln', amount: 2, unit: 'Stk', category: 'produce', order: 5 },
      { id: generateId(), name: 'Eier', amount: 3, unit: 'Stk', category: 'dairy', order: 6 },
      { id: generateId(), name: 'Sahne', amount: 200, unit: 'ml', category: 'dairy', order: 7 },
      { id: generateId(), name: 'Milch', amount: 100, unit: 'ml', category: 'dairy', order: 8 },
      { id: generateId(), name: 'Muskat', amount: 0.25, unit: 'TL', category: 'pantry', order: 9 },
      { id: generateId(), name: 'Pfeffer', amount: 0.5, unit: 'TL', category: 'pantry', order: 10 },
      { id: generateId(), name: 'Butter (zum Braten)', amount: 10, unit: 'g', category: 'dairy', order: 11 },
    ],
    instructions: [
      { step: 1, text: 'Mehl, kalte Butter in Stücken, Ei und Salz zu einem glatten Teig verkneten.' },
      { step: 2, text: 'Teig in Folie wickeln und 30 Minuten kalt stellen.' },
      { step: 3, text: 'Ofen auf 200°C vorheizen.' },
      { step: 4, text: 'Speck in einer Pfanne knusprig braten, herausnehmen.' },
      { step: 5, text: 'Zwiebeln in dünne Ringe schneiden und im Speckfett glasig dünsten.' },
      { step: 6, text: 'Teig ausrollen und in eine gefettete Tarteform (26cm) legen.' },
      { step: 7, text: 'Boden mit einer Gabel mehrfach einstechen.' },
      { step: 8, text: 'Speck und Zwiebeln auf dem Teigboden verteilen.' },
      { step: 9, text: 'Eier, Sahne, Milch, Muskat, Salz und Pfeffer verquirlen.' },
      { step: 10, text: 'Guss über die Füllung gießen.' },
      { step: 11, text: 'Im Ofen ca. 35-40 Minuten backen, bis die Füllung gestockt ist.' },
      { step: 12, text: 'Warm oder lauwarm servieren.' },
    ],
    nutrition: {
      calories: '380 kcal',
      protein: '14g',
      carbs: '24g',
      fat: '26g',
    },
    isFavorite: false,
    createdAt: Date.now(),
    updatedAt: Date.now(),
  },
  {
    id: generateId(),
    name: 'Gemischter Salat mit Hähnchen',
    description: 'Bunter Salat mit gegrilltem Hähnchenbrustfilet und hausgemachtem Dressing.',
    image: 'https://images.unsplash.com/photo-1512621776951-a57141f2eefd?w=800',
    prepTime: 20,
    cookTime: 15,
    totalTime: 35,
    servings: 2,
    category: 'Salat',
    cuisine: 'International',
    tags: ['Salat', 'Gesund', 'Hähnchen', 'Leicht'],
    ingredients: [
      { id: generateId(), name: 'Hähnchenbrustfilet', amount: 300, unit: 'g', category: 'meat', order: 0 },
      { id: generateId(), name: 'Eisbergsalat', amount: 0.5, unit: 'Kopf', category: 'produce', order: 1 },
      { id: generateId(), name: 'Rucola', amount: 100, unit: 'g', category: 'produce', order: 2 },
      { id: generateId(), name: 'Tomaten', amount: 4, unit: 'Stk', category: 'produce', order: 3 },
      { id: generateId(), name: 'Gurke', amount: 1, unit: 'Stk', category: 'produce', order: 4 },
      { id: generateId(), name: 'rote Zwiebel', amount: 0.5, unit: 'Stk', category: 'produce', order: 5 },
      { id: generateId(), name: 'Avocado', amount: 1, unit: 'Stk', category: 'produce', order: 6 },
      { id: generateId(), name: 'Mais (Dose)', amount: 150, unit: 'g', category: 'pantry', order: 7 },
      { id: generateId(), name: 'Olivenöl', amount: 4, unit: 'EL', category: 'pantry', order: 8 },
      { id: generateId(), name: 'Balsamico', amount: 2, unit: 'EL', category: 'pantry', order: 9 },
      { id: generateId(), name: 'Honig', amount: 1, unit: 'TL', category: 'pantry', order: 10 },
      { id: generateId(), name: 'Senf', amount: 1, unit: 'TL', category: 'pantry', order: 11 },
      { id: generateId(), name: 'Paprikapulver', amount: 0.5, unit: 'TL', category: 'pantry', order: 12 },
      { id: generateId(), name: 'Salz', amount: 1, unit: 'TL', category: 'pantry', order: 13 },
      { id: generateId(), name: 'Pfeffer', amount: 0.5, unit: 'TL', category: 'pantry', order: 14 },
    ],
    instructions: [
      { step: 1, text: 'Hähnchenbrust mit Paprikapulver, Salz und Pfeffer würzen.' },
      { step: 2, text: 'In einer Pfanne mit etwas Öl von beiden Seiten ca. 6-7 Minuten braten, bis durchgegart.' },
      { step: 3, text: 'Herausnehmen und in Streifen schneiden.' },
      { step: 4, text: 'Für das Dressing: Öl, Balsamico, Honig, Senf, Salz und Pfeffer verrühren.' },
      { step: 5, text: 'Salat waschen und in mundgerechte Stücke reißen.' },
      { step: 6, text: 'Tomaten vierteln, Gurke in Scheiben, Zwiebel in Ringe schneiden.' },
      { step: 7, text: 'Avocado halbieren, entkernen und in Scheiben schneiden.' },
      { step: 8, text: 'Alle Salatzutaten in einer großen Schüssel vermischen.' },
      { step: 9, text: 'Dressing darüberträufeln und vorsichtig unterheben.' },
      { step: 10, text: 'Mit Hähnchenstreifen anrichten.' },
    ],
    nutrition: {
      calories: '380 kcal',
      protein: '32g',
      carbs: '18g',
      fat: '22g',
    },
    isFavorite: true,
    createdAt: Date.now(),
    updatedAt: Date.now(),
  },
  {
    id: generateId(),
    name: 'Käsespätzle',
    description: 'Hausgemachte Spätzle mit geschmolzenem Käse und knusprigen Röstzwiebeln.',
    image: 'https://images.unsplash.com/photo-1585325701956-60dd9c8553bc?w=800',
    prepTime: 30,
    cookTime: 20,
    totalTime: 50,
    servings: 4,
    category: 'Hauptgericht',
    cuisine: 'Schwäbisch',
    tags: ['Spätzle', 'Käse', 'Vegetarisch', 'Herzhaft'],
    ingredients: [
      { id: generateId(), name: 'Mehl', amount: 400, unit: 'g', category: 'pantry', order: 0 },
      { id: generateId(), name: 'Eier', amount: 4, unit: 'Stk', category: 'dairy', order: 1 },
      { id: generateId(), name: 'Wasser (lauwarm)', amount: 200, unit: 'ml', category: 'beverages', order: 2 },
      { id: generateId(), name: 'Salz', amount: 1, unit: 'TL', category: 'pantry', order: 3 },
      { id: generateId(), name: 'Muskat', amount: 0.5, unit: 'TL', category: 'pantry', order: 4 },
      { id: generateId(), name: 'Emmentaler (gerieben)', amount: 300, unit: 'g', category: 'dairy', order: 5 },
      { id: generateId(), name: 'Zwiebeln', amount: 3, unit: 'Stk', category: 'produce', order: 6 },
      { id: generateId(), name: 'Butter', amount: 50, unit: 'g', category: 'dairy', order: 7 },
      { id: generateId(), name: 'Butter (zum Anbraten)', amount: 30, unit: 'g', category: 'dairy', order: 8 },
    ],
    instructions: [
      { step: 1, text: 'Mehl, Eier, Wasser, Salz und Muskat zu einem glatten, zähflüssigen Teig verrühren.' },
      { step: 2, text: 'Teig 15 Minuten quellen lassen.' },
      { step: 3, text: 'Zwiebeln in feine Ringe schneiden.' },
      { step: 4, text: 'Butter in einer Pfanne erhitzen und Zwiebeln bei mittlerer Hitze goldbraun rösten.' },
      { step: 5, text: 'Zwiebeln herausnehmen und beiseite stellen.' },
      { step: 6, text: 'Großen Topf mit gesalzenem Wasser zum Kochen bringen.' },
      { step: 7, text: 'Spätzleteig portionsweise durch ein Spätzlebrett oder eine Presse ins kochende Wasser schaben.' },
      { step: 8, text: 'Sobald die Spätzle oben schwimmen, mit einem Schaumlöffel herausnehmen.' },
      { step: 9, text: 'Abgetropfte Spätzle in einer gefetteten Auflaufform schichten, dazwischen Käse streuen.' },
      { step: 10, text: 'Im vorgeheizten Ofen bei 200°C ca. 10 Minuten überbacken, bis der Käse geschmolzen ist.' },
      { step: 11, text: 'Mit Röstzwiebeln bestreuen und sofort servieren.' },
    ],
    nutrition: {
      calories: '580 kcal',
      protein: '26g',
      carbs: '52g',
      fat: '32g',
    },
    isFavorite: true,
    createdAt: Date.now(),
    updatedAt: Date.now(),
  },
];

// Get all sample recipes
export const getSampleRecipes = (): Recipe[] => {
  return deepClone(sampleRecipes);
};

// Get favorite recipes
export const getFavoriteRecipes = (): Recipe[] => {
  return sampleRecipes.filter((r) => r.isFavorite);
};

// Get recipes by category
export const getRecipesByCategory = (category: string): Recipe[] => {
  return sampleRecipes.filter((r) => r.category === category);
};

// Get recipes by tag
export const getRecipesByTag = (tag: string): Recipe[] => {
  return sampleRecipes.filter((r) => r.tags.includes(tag));
};

// Get recipe by name (partial match)
export const searchRecipesByName = (query: string): Recipe[] => {
  const lowerQuery = query.toLowerCase();
  return sampleRecipes.filter((r) =>
    r.name.toLowerCase().includes(lowerQuery)
  );
};

// Get random recipe
export const getRandomRecipe = (): Recipe | null => {
  if (sampleRecipes.length === 0) return null;
  const randomIndex = Math.floor(Math.random() * sampleRecipes.length);
  return deepClone(sampleRecipes[randomIndex]);
};

// Import deepClone from utils
const deepClone = <T>(obj: T): T => {
  if (obj === null || typeof obj !== 'object') {
    return obj;
  }

  if (obj instanceof Date) {
    return new Date(obj.getTime()) as unknown as T;
  }

  if (Array.isArray(obj)) {
    return obj.map((item) => deepClone(item)) as unknown as T;
  }

  if (obj instanceof Object) {
    const copy = {} as T;
    for (const key in obj) {
      if (Object.prototype.hasOwnProperty.call(obj, key)) {
        copy[key] = deepClone(obj[key]);
      }
    }
    return copy;
  }

  return obj;
};

export default {
  sampleRecipes,
  getSampleRecipes,
  getFavoriteRecipes,
  getRecipesByCategory,
  getRecipesByTag,
  searchRecipesByName,
  getRandomRecipe,
};
